server:
  port: 8000


spring:
  application:
    name: mrbank

  datasource:
    url: jdbc:postgresql://localhost:5432/mrbank
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

application:
  security:
    jwt:
      secret: "bXItdGVtcG9yYXJ5LWxvY2FsLWRldi1qd3Qtc2VjcmV0LWtleS1tdXN0LWJlLWxvbmc="
      access-token-expiration: 15m
      refresh-token-expiration: 7d
